// Bundle canonical exports; json-schema-to-typescript owns all type translation.
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { compile } from "json-schema-to-typescript";

const root = fileURLToPath(new URL("../../../", import.meta.url));
const { values } = parseArgs({ options: {
  check: { type: "boolean", default: false },
  "schema-dir": { type: "string", default: resolve(root, "schemas") },
  output: { type: "string", default: resolve(root, "apps/web/src/generated/domain.ts") },
} });

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])]));
  }
  return value;
}

async function generate() {
  const definitions = {};
  const roots = [];
  function add(name, schema) {
    const normalized = canonical(schema);
    if (Object.hasOwn(definitions, name) &&
        JSON.stringify(definitions[name]) !== JSON.stringify(normalized)) {
      throw new Error(`Incompatible definition collision: ${name}`);
    }
    definitions[name] = normalized;
  }
  const files = (await readdir(values["schema-dir"])).filter(f => f.endsWith(".schema.json")).sort();
  if (!files.length) throw new Error("No canonical schemas found");
  for (const file of files) {
    const { $defs = {}, ...schema } = JSON.parse(await readFile(resolve(values["schema-dir"], file), "utf8"));
    for (const [name, definition] of Object.entries($defs)) add(name, definition);
    const name = file.slice(0, -".schema.json".length);
    if (schema.$ref === `#/$defs/${name}` && Object.keys(schema).length === 1) {
      if (!Object.hasOwn(definitions, name)) throw new Error(`Missing root definition: ${name}`);
    } else {
      add(name, schema);
    }
    roots.push({ $ref: `#/$defs/${name}` });
  }
  const output = await compile({ anyOf: roots, $defs: canonical(definitions) }, "QualorDomain", {
    bannerComment: "/** Generated by json-schema-to-typescript from schemas/*.schema.json.\n * DO NOT EDIT. Run scripts/generate-types.ps1.\n * Serialization shapes only; Python runtime validators remain authoritative.\n */",
    unreachableDefinitions: true,
    $refOptions: { resolve: { http: false, file: false } },
    style: { endOfLine: "lf" },
  });
  const bytes = Buffer.from(output.replaceAll("\r\n", "\n"), "utf8");
  if (values.check) {
    let existing;
    try { existing = await readFile(values.output); } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    if (!existing?.equals(bytes)) throw new Error("TYPE_CODEGEN=DRIFT");
  } else {
    await mkdir(dirname(resolve(values.output)), { recursive: true });
    await writeFile(values.output, bytes);
  }
  console.log(`TYPE_CODEGEN=PASS\nSCHEMA_FILES=${files.length}`);
}

generate().catch(error => { console.error(error.message); process.exitCode = 1; });
